apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:1.0.0
        env:
        - name: DB_HOST
          value: 'my-database-cluster-rw'  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-database-cluster-app 
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-database-cluster-app  
              key: password
        ports:
        - containerPort: 8080
