description: "Example of cluster"
imageName: quay.io/enterprisedb/postgresql:15.3
instances: 3
startDelay: 300
stopDelay: 300
primaryUpdateStrategy: unsupervised
resources:
  requests:
    memory: "512Mi"
    cpu: "1"
  limits:
    memory: "1Gi"
    cpu: "2"
postgresql:
  parameters:
    shared_buffers: 256MB
    pg_stat_statements.max: '10000'
    pg_stat_statements.track: all
    auto_explain.log_min_duration: '10s'
bootstrap:
  initdb:
    database: app
    owner: app
    secret:
      name: cluster-example-app-user
storage:
  storageClass: standard
  size: 1Gi
