apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: acme-postgres
  labels:
    provider: acme
    dplt.platform.io/type: postgres
spec:
  compositeTypeRef:
    apiVersion: dplt.platform.io/v1
    kind: AcmePostgres
  resources:
    - base:
        apiVersion: postgresql.k8s.enterprisedb.io/v1
        kind: Cluster
        spec: 
          instances: 3
          storage:
            size: "1Gi"
          imageName: "quay.io/enterprisedb/postgresql:14.2" # default image
          bootstrap:
            initdb:
              database: "app"
      patches:
        - fromFieldPath: spec.parameters.dbName
          toFieldPath: spec.bootstrap.initdb.database
        - fromFieldPath: spec.parameters.count
          toFieldPath: spec.instances
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageSizeMb
          toFieldPath: spec.storage.size
          transforms:
            - type: string
              string:
                fmt: "%sMi"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.version
          toFieldPath: spec.imageName
          transforms:
            - type: string
              string:
                fmt: "quay.io/enterprisedb/postgresql:%s"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.version
          toFieldPath: spec.imageName
          appliesTo:
            - fromFieldPath: spec.parameters.postgisEnabled
              policy: MustBeTrue
          transforms:
            - type: string
              string:
                fmt: "ghcr.io/cloudnative-pg/postgis:%s"
        - fromFieldPath: "spec.parameters.postgisEnabled"
          toFieldPath: spec.bootstrap.initdb.postInitTemplateSQL
          appliesTo:
            - fromFieldPath: spec.parameters.postgisEnabled
              policy: MustBeTrue
          transforms:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: "spec.parameters.postgisEnabled"
                strategy: String
                string:
                  fmt: |
                    "CREATE EXTENSION postgis;
                    CREATE EXTENSION postgis_topology;
                    CREATE EXTENSION fuzzystrmatch;
                    CREATE EXTENSION postgis_tiger_geocoder;"
