apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: acme-postgres-claim-postgis
  namespace: default
  labels:
    crossplane.io/composite: acme-postgres-claim-postgis
spec: 
  instances: 5
  storage:
    size: "3000Mi"
  imageName: "ghcr.io/cloudnative-pg/postgis:15.2"
  bootstrap:
    initdb:
      database: "dpro1"
      postInitTemplateSQL:
        - "CREATE EXTENSION postgis;"
        - "CREATE EXTENSION postgis_topology;"
        - "CREATE EXTENSION fuzzystrmatch;"
        - "CREATE EXTENSION postgis_tiger_geocoder;"
