apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: my-cluster
spec:
  instances: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"

  storage:
    size: 5Gi